version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: IsoBridge.Web/Dockerfile
    ports:
      - "8080:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./IsoBridge.Web/appsettings.Development.json:/app/appsettings.Development.json
      - ./IsoBridge.Web/Config:/app/Config
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./data:/data
